In [26]:
import os

# Set the path to the folder containing your data
folder_path = r'D:\Documentos\Semestre8\Aplicaciones avanzadas\AI\Proyecto\AImodel\images\train'

# Iterate over each subfolder
for subfolder in os.listdir(folder_path):
    subfolder_path = os.path.join(folder_path, subfolder)
    if os.path.isdir(subfolder_path):
        # Count the number of files in the subfolder
        file_count = len(os.listdir(subfolder_path))

        print(f"Folder: {subfolder} - Number of Files: {file_count}")


Folder: alfa romeo - Number of Files: 444
Folder: Audi - Number of Files: 324
Folder: Bentley - Number of Files: 410
Folder: Benz - Number of Files: 255
Folder: Bmw - Number of Files: 277
Folder: Cadillac - Number of Files: 384
Folder: Dodge - Number of Files: 373
Folder: Ferrari - Number of Files: 358
Folder: Ford - Number of Files: 373
Folder: Ford mustang - Number of Files: 433
Folder: hyundai - Number of Files: 318
Folder: Kia - Number of Files: 365
Folder: Lamborghini - Number of Files: 419
Folder: Lexus - Number of Files: 397
Folder: Maserati - Number of Files: 421
Folder: Porsche - Number of Files: 307
Folder: Rolls royce - Number of Files: 384
Folder: Tesla - Number of Files: 261
Folder: Toyota - Number of Files: 317


In [21]:
import numpy as np 

preddic = [[1,1], [1,0], [0,1], [0,0], [0,1], [1,1], [1,1]]
sum = 0
matriz = np.zeros((2, 2))
for i in preddic:
   if i[0] == 1 and i[1] == 1:
      matriz[0][0] += 1
   elif i[0] == 0 and i[1] == 0:
      matriz[1][1] += 1 
   elif i[0] == 1 and i[1] == 0:
      matriz[1][0] += 1 
   elif i[0] == 0 and i[1] == 1:
      matriz[0][1] += 1 

print(matriz)
print(matriz[0][0]/(matriz[0][0]+matriz[0][1]))

[[3. 2.]
 [1. 1.]]
0.6


In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_data_dir = r'D:\Documentos\Semestre8\Aplicaciones avanzadas\AI\Proyecto\AImodel\images\train'
test_data_dir = r'D:\Documentos\Semestre8\Aplicaciones avanzadas\AI\Proyecto\AImodel\images\test'
validation_data_dir = r'D:\Documentos\Semestre8\Aplicaciones avanzadas\AI\Proyecto\AImodel\images\validation'

total_train_samples = sum([len(files) for _, _, files in os.walk(train_data_dir)])

train_datagen = ImageDataGenerator(1./255)  

test_datagen = ImageDataGenerator(1./255)   

validation_datagen = ImageDataGenerator(1./255)  

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(150, 150),
    batch_size=40,
    class_mode='categorical')

test_generator = test_datagen.flow_from_directory(
    test_data_dir,
    target_size=(150, 150),
    batch_size=2000,
    class_mode='categorical')

validation_generator = validation_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(150, 150),
    batch_size=20,
    class_mode='categorical')



Found 6820 images belonging to 19 classes.
Found 2282 images belonging to 19 classes.
Found 2278 images belonging to 19 classes.


In [21]:
from tensorflow.keras import optimizers
from tensorflow.keras import models
from tensorflow.keras import layers

model = models.Sequential()
model.add(layers.Conv2D(10, (3, 3), activation="relu", input_shape = (150,150,3)))
model.add(layers.Flatten())
model.add(layers.Dense(256,activation='relu'))
model.add(layers.Dense(19,activation='sigmoid'))

model.summary()

model.compile(loss='categorical_crossentropy',
						optimizer='Adam',
						metrics=['acc'])

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 148, 148, 10)      280       
                                                                 
 flatten_11 (Flatten)        (None, 219040)            0         
                                                                 
 dense_23 (Dense)            (None, 256)               56074496  
                                                                 
 dense_24 (Dense)            (None, 19)                4883      
                                                                 
Total params: 56,079,659
Trainable params: 56,079,659
Non-trainable params: 0
_________________________________________________________________


In [22]:
history = model.fit_generator(train_generator, 
				steps_per_epoch =total_train_samples/40,  
				epochs =10,
                validation_data=validation_generator,
            	validation_steps=8 
				)

Epoch 1/10


C:\Users\joako\AppData\Local\Temp\ipykernel_10644\1183620081.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = model.fit_generator(train_generator,


170/170 [==============================] - 122s 713ms/step - loss: 1297.5839 - acc: 0.0930 - val_loss: 14.0885 - val_acc: 0.1500
Epoch 2/10
170/170 [==============================] - 120s 702ms/step - loss: 3.0110 - acc: 0.7031 - val_loss: 13.4497 - val_acc: 0.1375
Epoch 3/10
170/170 [==============================] - 116s 680ms/step - loss: 0.7464 - acc: 0.9235 - val_loss: 14.1762 - val_acc: 0.1813
Epoch 4/10
170/170 [==============================] - 114s 670ms/step - loss: 0.5353 - acc: 0.9654 - val_loss: 15.3066 - val_acc: 0.2062
Epoch 5/10
170/170 [==============================] - 114s 667ms/step - loss: 0.5546 - acc: 0.9611 - val_loss: 16.1352 - val_acc: 0.2000
Epoch 6/10
170/170 [==============================] - 114s 669ms/step - loss: 0.7028 - acc: 0.9614 - val_loss: 22.5905 - val_acc: 0.1750
Epoch 7/10
170/170 [==============================] - 114s 671ms/step - loss: 0.4978 - acc: 0.9696 - val_loss: 17.2771 - val_acc: 0.1875
Epoch 8/10
170/170 [=============================

In [23]:
test_loss, test_acc = model.evaluate(test_generator, steps = 1)
print('\ntest acc :\n', test_acc)

1/1 [==============================] - 9s 9s/step - loss: 21.1681 - acc: 0.1820

test acc :
 0.18199999630451202


In [25]:
import numpy as np
test_imgs = test_generator[0][0]
test_labels = test_generator[0][1]


predictions = model.predict(test_imgs)
classes_x = np.argmax(predictions,axis=1)
classex_y = np.argmax(test_labels,axis=1)

from tensorflow.math import confusion_matrix
mat = confusion_matrix(classes_x, classex_y)
print(mat) 

63/63 [==============================] - 2s 38ms/step
tf.Tensor(
[[18  4  4  7  9  5  2  2  4  5  3  1  6  2  3  4  8  5  3]
 [ 3 15  3  6  3  8  2 10 10  4  4  4  4  9  5  2  5  5  5]
 [ 3  3  7  0  1  3  1  3  2  2  1  1  2  1  5  1  3  1  1]
 [ 2  4  0  9  5  1  2  3  2  5  5  1  4  5  2  1  3  5  1]
 [ 7  8  7  2 17  8  2  4  5  7 11  7 14  0  7  4  7  4  6]
 [ 0  1  1  1  3 18  5  2  1  3  1  2  1  2  2  1  0  1  1]
 [ 6  9  3  4 10 17 49 13 15  8 24  7  9  9  6 17 11 23 11]
 [ 4  3  1  2  7  6  1 19  2  8  6  5  5  3  6  5  3  4  8]
 [ 1  3  3  3  1  2  2  6 15  2  4  1  1  3  1  0  1  1  3]
 [ 8 17 14 10 13  9  7 11 11 23  7 20  2 10  9  2 15  7  8]
 [ 2  1  0  2  2  0  1  2  4  1 16  5  0  3  2  2  1  1  1]
 [10  3  1  6  8  4  5  4  7  6  7 18 11  2 14  2  5  3  7]
 [ 4  3  2  4  3  3  5  4  4  3  3  6 16  4  3  1  3  3  4]
 [ 8 15  8  6  4  5  6  5  7  7 11  9 12 27 11  7  5  8  7]
 [ 3  5  3  1  3  2  0  3  7  0  3  7 11  3 19  1  3  4  1]
 [ 3  6  2  0  3  4  6  5  4  3  1 